version: '3.7'
services:
  postgres-register:
    container_name: postgres-register-quarkusfood
    image: postgres:latest
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
    ports:
      - 5432:5432

