quarkus:
  datasource:
    db-kind: postgresql
    username: register
    password: register
    jdbc:
      url: jdbc:postgresql://localhost/register
      driver: org.postgresql.Driver
  hibernate-orm:
    database:
      generation: drop-and-create

"%test":
  quarkus:
    datasource:
      db-kind: h2
      username: test
      password: test
      jdbc:
        url: jdbc:h2:mem:test
        driver: org.h2.Driver
    hibernate-orm:
      database:
        generation: update
